name = "re-Terminal"
license = "MIT"
licenselink = "https://github.com/olsyx/hugo-theme-re-terminal/blob/main/LICENSE.md"
description = "A simple, retro theme for Hugo."
homepage = "https://github.com/olsyx/hugo-theme-re-terminal/"
demosite = "https://re-terminal.nebrowser.com"
tags = [
  "blog",
  "clean",
  "customizable",
  "dark",
  "highlighting",
  "minimal",
  "monotone",
  "multilingual",
  "personal",
  "responsive",
  "simple",
  "technical",
  "retro",
]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.128

[author]
name = "Olsyx"
homepage = ""

[original]
name = "Mirus"
homepage = "https://nebrowser.com"
repo = "https://github.com/mirus-ua/hugo-theme-re-terminal/"
